# Generated by Django 5.2.17 on 2026-08-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isAvaialble',
            new_name='isAvailable',
        ),
    ]
