# Generated by Django 5.2.17 on 2026-08-31 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productimage_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.productcolor'),
        ),
    ]
