# Generated by Django 5.2.17 on 2026-08-31 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productimage_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.productcolor'),
        ),
    ]
