# Generated by Django 5.2.17 on 2026-08-31 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_productimage_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.productcolor'),
        ),
    ]
