# Generated by Django 5.2.17 on 2026-09-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_brand_product_is_on_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
